<?php
	
/*
	Question2Answer 1.4.1 (c) 2011, Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-admin.php
	Version: 1.4.1
	Date: 2011-07-10 06:58:57 GMT
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => 'Os seguintes widgets estão atualmente ativos:',
		'add_category_button' => 'Adicionar Categoria',
		'add_field_button' => 'Adicionar campo',
		'add_link_button' => 'Adicionar link',
		'add_link_link' => ' - ^1adicionar link^2',
		'add_new_field' => 'Adicionar um novo campo',
		'add_new_title' => 'Adicionar um novo título',
		'add_page_button' => 'Adicionar página',
		'add_title_button' => 'Adicionar título',
		'add_widget_button' => 'Adicionar Widget',
		'add_widget_link' => ' - ^1adicionar Widget^2',
		'admin_title' => 'Administração',
		'after_footer' => 'Depois dos links no rodaé',
		'after_main_menu' => 'Depois das abas no topo',
		'after_x_tab' => 'Depois "^" aba',
		'after_x' => 'Depois "^"',
		'basic_editor' => 'Editor básico',
		'before_main_menu' => 'Antes das abas no topo',
		'block_ips_note' => 'Use um hífen para faixas de ip ou * para qualquer número. Exemplos: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => 'Use um * para qualquer letra. Exemplos: doh (funciona apenas para a palavra doh) , doh* (funciona para doh or dohno) , do*h (funciona para doh, dooh, dough).',
		'categories_introduction' => 'Para criar categorias, clique no botão \'Adicionar categoria\'.',
		'categories_not_shown' => 'Algumas perguntas tem categorias não qual não serão exibidas.',
		'categories_title' => 'Categorias',
		'categories' => 'Categorias',
		'category_add_sub' => 'adicionar sub-categoria',
		'category_added' => 'Categoria Adicionada',
		'category_already_used' => 'Esta categoria já está sendo usada',
		'category_default_slug' => 'categoria-^',
		'category_description' => 'Descrição da categoria (opcional):',
		'category_max_depth_x' => 'Algumas opções podem estar ocultas para prevenir que uma categoria tenha ^ níveis ',
		'category_move_parent' => 'mover para uma categoria pai',
		'category_name_first' => 'Nome da primeira categoria:',
		'category_name' => 'Nome da categoria:',
		'category_no_add_subs_x' => 'Esta categoria não pode ter sub categorias pois já atingiu ^ níveis.',
		'category_no_delete_subs' => 'Esta categoria não pode ser apagada porque tem sub-categorias.',
		'category_no_sub_error' => '^q Perguntas nesta categoria não tem sub categorias - ^1 informar subcategoria ^2',
		'category_no_sub_to' => 'Mover perguntas em ^ sem categorias para:',
		'category_no_subs' => 'Nada',
		'category_none_error' => '^q perguntas sem categorias - ^1 informar categoria ^2',
		'category_none_to' => 'Mover perguntas sem categoria para:',
		'category_parent' => 'Categoria pai:',
		'category_saved' => 'Categoria guardada',
		'category_slug' => 'Categoria slug (fragmento da URL):',
		'category_subs' => 'Sub categorias:',
		'category_top_level' => 'Sem pais (nível mais alto)',
		'click_category_edit' => 'Clique no nome da categoria para editá-la:',
		'click_name_edit' => 'Páginas ou links:',
		'database_cleanup' => 'Operação de limpeza do banco de dados',
		'delete_category_reassign' => 'Apagar esta categoria e reatribuir as perguntas para:',
		'delete_category' => 'Apagar esta categoria',
		'delete_field' => 'Apagar este campo',
		'delete_hidden_complete' => 'Todos os posts ocultos sem dependências foram apagados',
		'delete_hidden_note' => ' - todas as perguntas ocultas, respostas e comentários sem dependências',
		'delete_hidden' => 'Apagar posts ocultos',
		'delete_link' => 'Apagar este link',
		'delete_page' => 'Apagar esta página',
		'delete_stop' => 'Parar de apagar',
		'delete_title' => 'Apagar este título',
		'delete_widget_position' => 'Apagar este widget desta posição',
		'edit_custom_page' => 'Editar página customizada',
		'edit_field' => ' - ^1editar campo^2',
		'edit_link' => ' - ^1editar link^2',
		'edit_page' => ' - ^1editar página^2',
		'edit_title' => ' - ^1editar título^2',
		'emails_title' => 'Emails',
		'feed_link_example' => 'Exemplo de feed',
		'feed_link' => 'Feed',
		'feeds_title' => 'RSS feeds',
		'field_link_url' => 'Linked URL',
		'field_multi_line' => 'Múltiplas linhas de texto',
		'field_name' => 'Nome do campo para exibição',
		'field_single_line' => 'Linha de texto simples',
		'field_type' => 'Tipo de campo:',
		'first' => 'Prmeiro',
		'from_anon' => 'De anônimo:',
		'from_plugin_module' => ' (do módulo de plugin: ^)',
		'from_users' => 'De utilizadores:',
		'general_title' => 'Geral',
		'hidden_answers_deleted' => 'Apagar ^1 de ^2 respostas ocultas sem dependências',
		'hidden_comments_deleted' => 'Apagar ^1 of ^2 comentários ocultos...',
		'hidden_questions_deleted' => 'Apagar ^1 of ^2 perguntas respondidas sem dependências',
		'hidden_title' => 'Oculto',
		'installed_plugins' => 'Plugins instalados:',
		'ip_address_pages' => 'Página de enderecos IPs',
		'layout_title' => 'Layout',
		'link_name' => 'Texto do link:',
		'link_new_window' => 'Abrir link em uma nova janela',
		'link_url' => 'URL do link (absoluto ou relativo):',
		'lists_title' => 'Listas',
		'maintenance_admin_only' => 'Seu site está em ^1manutenção^2 e atualmente está inacessível para os utilizadores.',
		'maximum_x' => ' (max ^)',
		'mysql_version' => 'Versão do MySQL:',
		'nav_links_explanation' => 'Exibindo os seguintes links de navegação para cada página.',
		'nav_qa_is_home' => 'Q&A (links para página principal)',
		'neat_urls_note' => ' (requer o arquivo ^1htaccess^2)',
		'no_classification' => 'Sem classificação',
		'no_hidden_found' => 'Sem perguntas, respostas ou comentários ocultos.',
		'no_image_gd' => 'A versão do PHP instalada não possui suporte a biblioteca GD para manipulação de imagem, então utilizadores não podem enviar avatares diretamente.',
		'no_link' => 'Sem link',
		'no_multibyte' => 'A versão do PHP instalada nao tem suporte a string multibyte. Busca será menos eficiente para caracteres não romanos.',
		'no_plugin_options' => 'Nenhum dos seus plugins instalados tem opções para exibir.',
		'no_privileges' => 'Somente administradores tem acesso a esta página.',
		'not_logged_in' => 'Por favor ^1logue^2 como administrador para acessar esta página.',
		'opposite_main_menu' => 'Mais longe do final das abas',
		'options_reset' => 'Opções restauradas',
		'options_saved' => 'Opções guardadas',
		'page_already_used' => 'Já está sendo usado pela página',
		'page_content_html' => 'Conteúdo exibido na página (HTML permitido):',
		'page_default_slug' => 'página-^',
		'page_heading' => 'Cabeçalho exibido no topo da página:',
		'page_name' => 'Nome da página (também usado em uma aba ou link):',
		'page_slug' => 'Página slug (fragmento da URL):',
		'pages_explanation' => 'Clique no botão \'Adicionar página\' para adicionar um conteúdo customizado no seu site, ou \'Adicionar links\' para adicionar um link para outro site.',
		'pages_title' => 'Páginas',
		'permissions_title' => 'Permissões',
		'php_version' => 'Versão do PHP:',
		'plugin_pages_explanation' => 'As seguintes páginas estão disponíveis via plugins:',
		'plugin_widgets_explanation' => 'Os seguintes widgets estão disponíveis via plugins:',
		'plugins_title' => 'Plugins',
		'points_defaults_shown' => 'Padrões aparecem a seguir mas nao são aplicados:',
		'points_required' => 'Pontos necessários para receber um título:',
		'points_title' => 'Pontos',
		'points' => 'pontos',
		'position' => 'Posição:',
		'posting_title' => 'Postando',
		'profile_fields' => 'Campos extras no profile do utilizador:',
		'q2a_db_version' => 'Q2A versão do banco:',
		'q2a_latest_version' => 'Q2A última versão:',
		'q2a_version' => 'Question2Answer versão:',
		'question_lists' => 'Lista de Perguntas',
		'question_pages' => 'Páginas de perguntas',
		'recalc_categories_backpaths' => 'Recalculando partes da URL para ^1 de ^2 categorias...',
		'recalc_categories_complete' => 'Todas as categorias foram atualizadas corretamente.',
		'recalc_categories_note' => ' - para postagens nas categorias',
		'recalc_categories_recounting' => 'Recalculando perguntas para  ^1 de ^2 categorias...',
		'recalc_categories_updated' => 'Recalculadas para ^1 de ^2 posts...',
		'recalc_categories' => 'Categorias recalculadas',
		'recalc_points_complete' => 'Todos os pontos do utilizador foram recalculados',
		'recalc_points_note' => ' - para ranking do utilizador e exibição de pontos',
		'recalc_points_recalced' => 'Recalculados para ^1 de ^2 utilizadores...',
		'recalc_points_usercount' => 'Número total de utilizadores estiamdos...',
		'recalc_points' => 'Pontos do utilizador recalculados',
		'recalc_posts_count' => 'Obtendo o total do número de perguntas, respostas e comentários...',
		'recalc_stop' => 'Parar',
		'recaptcha_fsockopen' => 'Para usar reCAPTCHA, a função PHP fsockopen() precisa estar ativada no servidor. Por favor cheque com o administrador.',
		'recaptcha_get_keys' => 'Para usar reCAPTCHA, você precisa ^1logar^2 para obter as keys.',
		'recent_hidden_title' => 'Questões com conteúdo oculto recentes',
		'recount_posts_complete' => 'Todos os posts foram recontados com sucesso.',
		'recount_posts_note' => ' - o número de respostas, votos e sinalizações para cada post',
		'recount_posts_recounted' => 'Recontando para ^1 de ^2 posts...',
		'recount_posts_stop' => 'Parar',
		'recount_posts' => 'Recontar posts',
		'reindex_posts_complete' => 'Todos os posts foram indexados com sucesso.',
		'reindex_posts_note' => ' - para buscas e sugestão de perguntas relacionadas',
		'reindex_posts_reindexed' => 'Reindexando ^1 de ^2 posts...',
		'reindex_posts_stop' => 'Parar',
		'reindex_posts_wordcounted' => 'Recontando ^1 de ^2 palavras...',
		'reindex_posts' => 'Reindexar posts',
		'requires_q2a_version' => 'Desativado - requer Question2Answer ^ ou superior',
		'reset_options_button' => 'Voltar para padrão',
		'save_options_button' => 'Guardar Opções',
		'save_recalc_button' => 'Guardar e recalcular',
		'show_defaults_button' => 'Exibir padrão',
		'slug_bad_chars' => 'O slug não pode conter estes caracteres: ^',
		'slug_reserved' => 'Este slug está reservado para uso em outra página',
		'spam_title' => 'Spam',
		'stats_title' => 'Status',
		'stop_recalc_warning' => 'Uma limpeza no banco de dados está acontecendo agora. Se você fechar esta página agora, a operação será interrompida.',
		'tag_pages' => 'Página de Tags',
		'tags_and_categories' => 'Tags e Categorias',
		'tags_not_shown' => 'Algumas perguntas possuem tags que não estão exibidas',//Some questions have tags which will not be displayed.',
		'tags' => 'Tags',
		'title_already_used' => 'Este valor jpa estpa sendo usado por outro tírulo',
		'total_as' => 'Total de respostas:',
		'total_cs' => 'Total de comentários:',
		'total_qs' => 'Total de perguntas:',
		'unnamed_plugin' => 'Plugin sem nome',
		'upgrade_db' => 'Seu banco de dados precisa ser ^1atualizado^2 para esta versão.',
		'url_format_note' => 'Opções com o label ^ estão funcionando na configuração do seu site. Para uma melhor otimização na busca(SEO), use a primeira ^ opção disponível.',
		'user_pages' => 'Página de utilizadores',
		'user_title' => 'Título (HTML permitido):',
		'user_titles' => 'Títulos baseados em pontos:',
		'users_active' => 'Utilizadores ativos:',
		'users_must_have' => 'Utilizadores precisam ter',
		'users_posted' => 'Quem postou:',
		'users_registered' => 'Utilizadores registrados:',
		'users_title' => 'Utilizadores',
		'users_voted' => 'Em quem os utilizadores votaram:',
		'viewing_title' => 'Vendo',
		'widget_all_pages' => 'Exibir widget no topo de todas as páginas disponíveis',
		'widget_global_options' => ' - ^1editar opções globais^2',
		'widget_name' => 'Nome do widget:',
		'widget_no_positions' => 'Este widget já está adicionado na posição escolhida.',
		'widget_not_available' => 'Este widget não está disponível. Isto pode acontecer porque o plugin nao está mais instalado.',
		'widget_pages_explanation' => 'Exibindo o widget na posição das seguintes páginas:',
		'moderate_title' => "Moderar",
		'cancel_mailing_button' => "Cancelar Mailing",
		'characters' => "caracteres",
		'check_language_suffix' => " - ^1verificar ficheiros de linguagem^2",
		'emails_per_minute' => "emails por minuto",
		'flagged_title' => "Marcados",
		'hotness_factors' => "Factores determinadores da importância das questões:",
		'mailing_complete' => "Mailing terminado",
		'mailing_explanation' => "Os utilizadores conseguirão cancelar a subscrição na página de conta.",
		'mailing_progress' => "Mailing enviado a ^1 de ^2 utilizadores...",
		'mailing_title' => "Mailing",
		'mailing_unsubscribe' => "Um link de cancelar subscrição será colocado no final de cada mensagem.",
		'module_x_database_init' => "O módulo ^1 ^2 necessita alguma ^3inicialização na base de dados^4.",
		'most_flagged_title' => "Conteúdo marcado",
		'no_approve_found' => "Não há conteúdos aguardando aprovação",
		'no_flagged_found' => "Não há conteúdos marcados",
		'options' => "Opções",
		'pause_mailing_button' => "Pausar Mailing",
		'per_ip_hour' => "por IP/hora",
		'per_user_hour' => "por utilizador/hora",
		'permit_to_view' => "Visível por:",
		'pixels' => "píxeis",
		'plugin_module' => " (módulo plugin: ^)",
		'q2a_build_date' => "Data de compilação:",
		'q2a_db_size' => "Tamanho da base de dados:",
		'recent_approve_title' => "Conteúdos recentes aguardando aprovação",
		'recount_posts_as_recounted' => "Recontadas respostas e importância para ^1 de ^2 posts...",
		'recount_posts_votes_recounted' => "Recontados votos e marcações para ^1 de ^2 posts...",
		'refill_events_complete' => "Todos os streams de eventos foram preenchidos com sucesso",
		'refill_events_note' => " - para a lista de atualizações de cada utilizador",
		'refill_events_refilled' => "Preenchidos para ^1 de ^2 perguntas...",
		'refill_events' => "Preencher streams de eventos",
		'reindex_content' => "Re-indexar conteúdo",
		'reindex_content_note' => " - para procuras e sugestões de questões relacionadas",
		'reindex_content_stop' => "Parar de re-indexar",
		'reindex_pages_reindexed' => "Re-indexadas ^1 de ^2 páginas...",
		'requires_php_version' => "Desactivado - requer PHP ^ ou superior",
		'resume_mailing_button' => "Continuar Mailing",
		'send_test_button' => "Enviar teste para mim",
		'start_mailing_button' => "Iniciar Mailing",
		'test_sent_to_x' => "A mensagem de teste foi enviada para ^",
		'top_level_categories' => "Categorias de topo:",
		'version_get_x' => "obter ^",
		'version_requires_php' => "^1 requer PHP ^2",
		'version_requires_q2a' => "^1 requer Q2A ^2",
		'version_latest_unknown' => "mais recente desconhecida",
		'version_latest' => "mais recente",
		'widgets_explanation' => "Widgets disponíveis:",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
