<?php
	
/*
	Question2Answer 1.4.1 (c) 2011, Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-options.php
	Version: 1.4.1
	Date: 2011-07-10 06:58:57 GMT
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => 'Permitir que usuários altere seu usuário nas mensagem:',
		'allow_multi_answers' => 'Permitem respostas múltiplas por usuário:',
		'allow_no_category' => 'Permitir perguntas sem categoria',
		'allow_no_sub_category' => 'Permitir perguntas com uma categoria, mas nenhuma sub-categoria',
		'allow_private_messages' => 'Permitem que os utilizadores enviar mensagens entre si:',
		'allow_view_q_bots' => 'Permitir os motores de busca para ver páginas de resposta',
		'avatar_allow_gravatar' => 'Permitir ^1Gravatar^2 avatares:',
		'avatar_allow_upload' => 'Permitir que usuários façam upload de avatares:',
		'avatar_default_show' => 'Mostrar avatar padrão:',
		'avatar_profile_size' => 'Tamanho do avatar na página do perfil de usuário (pixels):',
		'avatar_q_list_size' => 'Tamanho dos avatares em listas de interrogação (pixels):',
		'avatar_q_page_a_size' => 'Tamanho dos avatares nas respostas (pixels):',
		'avatar_q_page_c_size' => 'Tamanho de avatares nos comentários (pixels):',
		'avatar_q_page_q_size' => 'Tamanho dos avatares em perguntas (pixels):',
		'avatar_store_size' => 'Tamanho máximo de avatares armazenados (pixels):',
		'avatar_users_size' => 'Tamanho dos avatares nas páginas principais do usuários (pixels):',
		'block_bad_words' => 'Palavras censuradas (separados por espaços ou vírgulas):',
		'block_ips_write' => 'Bloquear os endereços de IP (separados por espaços ou vírgulas):',
		'captcha_on_anon_post' => 'Use reCAPTCHA para postagens anônimas:',
		'captcha_on_feedback' => 'Use reCAPTCHA no formulário de feedback:',
		'captcha_on_register' => 'Use reCAPTCHA para registro de usuário:',
		'captcha_on_reset_password' => 'Use reCAPTCHA em forma de redefinição de senha:',
		'captcha_on_unconfirmed' => 'Use reCAPTCHA para mensagens de e-mail se não for confirmado:',
		'columns_tags' => 'Tag colunas de página:',
		'columns_users' => 'Utilizadores colunas de página:',
		'comment_on_as' => 'Permitir comentários sobre as respostas:',
		'comment_on_qs' => 'Permitir comentários sobre perguntas:',
		'confirm_user_emails' => 'Confirmação de pedido de endereço de email do usuário:',
		'custom_home_content' => 'Conteúdo a ser exibido na home page (HTML permitido):',
		'custom_home_heading' => 'Título para mostrar no topo da página inicial:',
		'custom_welcome' => 'Mensagem personalizada para incluir no email enviado para novos usuários:',
		'default_privacy' => 'Privacidade: Seu endereço de email não será compartilhado ou vendido a terceiros.',
		'default_sidebar' => "Bem-vindo ao ^, onde você pode fazer perguntas e receber respostas de outros membros da comunidade.",
		'default_suffix' => 'Q&A',
		'do_ask_check_qs' => 'Verifique se há perguntas semelhantes ao perguntar:',
		'do_complete_tags' => 'Mostrar tags correspondentes ao digitar:',
		'do_count_q_views' => 'Conte o número de pontos de perguntas vista:',
		'do_example_tags' => 'Mostrar tags exemplo com base em pergunta:',
		'do_related_qs' => 'Mostrar as perguntas relacionadas na página de perguntas:',
		'editor_for_as' => 'Editor padrão de respostas:',
		'editor_for_cs' => 'Editor padrão para comentários:',
		'editor_for_qs' => 'Editor padrão para as perguntas:',
		'email_privacy' => 'Nota de privacidade para e-mail sobre todas as formas (HTML permitido):',
		'feed_for_activity' => 'Feed para nova atividade:',
		'feed_for_hot' => 'Feed para perguntas populares:',
		'feed_for_qa' => 'Feed para perguntas e respostas recentes:',
		'feed_for_questions' => 'Feed para perguntas recentes:',
		'feed_for_search' => 'Feeds para resultados de pesquisa:',
		'feed_for_tag_qs' => 'Feeds para perguntas recentes com cada tag:',
		'feed_for_unanswered' => 'Feed para recentes perguntas sem resposta:',
		'feed_full_text' => 'Incluir texto completo nos feeds:',
		'feed_number_items' => 'Número máximo de itens em freeds:',
		'feed_per_category' => 'Feeds para o exposto em cada categoria:',
		'feedback_email' => 'Endereço de email para mensagens de admin (não é mostrado aos usuários):',
		'feedback_enabled' => 'Fornecer um formulário para que os usuários enviem-me o gabarito',
		'flagging_hide_after' => 'Ocultar automaticamente as mensagens que chegam:',
		'flagging_notify_every' => 'Me avisa por e-mail depois de cada adicional novo:',
		'flagging_notify_first' => 'Me avisa por e-mail depois que recebe o primeiro post:',
		'flagging_of_posts' => 'Permitir mensagens para ser marcada como imprópria:',
		'follow_on_as' => 'Permitir que novas perguntas sejam relacionadas com respostas:',
		'from_email' => 'Endereço do remetente para todas as mensagens administrativa:',
		'hot_weight_a_age' => 'Peso da última resposta para as perguntas populares:',
		'hot_weight_answers' => 'Peso da última resposta para as perguntas populares (numero):',
		'hot_weight_q_age' => 'Peso da última pergunta para as perguntas populares:',
		'hot_weight_views' => 'Peso da última visita para as perguntas populares:',
		'hot_weight_votes' => 'Peso do último voto para as perguntas populares:',
		'links_in_new_window' => 'Abrir links em uma nova janela:',
		'logo_height' => 'Altura do logotipo em pixels:',
		'logo_show' => 'Mostrar uma imagem de logotipo no cabeçalho da página',
		'logo_url' => 'URL do logotipo (absolutos ou relativos à raiz QA):',
		'logo_width' => 'Largura do logotipo em pixels:',
		'match_1' => 'Mais estreita',
		'match_2' => 'Mais estreito',
		'match_3' => 'Padrão',
		'match_4' => 'Amplo',
		'match_5' => 'Mais amplo',
		'match_ask_check_qs' => 'Perguntas similares correspondência:',
		'match_example_tags' => 'Tag exemplo correspondência:',
		'match_related_qs' => 'perguntas relacionadas correspondência:',
		'max_len_q_title' => 'Máximo de caracteres no título da pergunta:',
		'max_num_q_tags' => 'Máximo de número de tags da pergunta:',
		'max_rate_ip_as' => 'Máximo de respostas por endereço de IP por hora:',
		'max_rate_ip_cs' => 'Máximo de comentários  por endereço de IP por hora:',
		'max_rate_ip_flags' => 'Máxima de flags por endereço de IP por hora:',
		'max_rate_ip_logins' => 'Máximo de tentativas de login por endereço de IP por hora:',
		'max_rate_ip_messages' => 'Máximo de mensagens privadas por endereço de IP por hora:',
		'max_rate_ip_qs' => 'Máximo de perguntas por endereço de IP por hora:',
		'max_rate_ip_uploads' => 'Máximo de imagens por endereço de IP por hora:',
		'max_rate_ip_votes' => 'Máximo de votos por endereço de IP por hora:',
		'max_rate_user_as' => 'Máximo de respostas por usuário por hora:',
		'max_rate_user_cs' => 'Máximo de resposta por usuário por hora:',
		'max_rate_user_flags' => 'Máximo de flags por usuário por hora:',
		'max_rate_user_messages' => 'Máximo de mensagens privadas por usuário por hora:',
		'max_rate_user_qs' => 'Máximo de perguntas por usuário por hora:',
		'max_rate_user_uploads' => 'Máximo de imagens por usuário por hora:',
		'max_rate_user_votes' => 'Máximo de votos por usuário por hora:',
		'min_len_a_content' => 'Mínimo de caracteres, em resposta:',
		'min_len_c_content' => 'Mínimo de caracteres, em comentário:',
		'min_len_q_content' => 'Mínimo de caracteres, no corpo da pergunta:',
		'min_len_q_title' => 'Mínimo de caracteres, no título da pergunta:',
		'min_num_q_tags' => 'Número mínimo de tags na pergunta:',
		'neat_urls' => 'Estrutura de URL para páginas em seu site:',
		'notify_admin_q_post' => 'Avisar por e-mail, quando uma pergunta é postado',
		'notify_users_default' => 'Caixa de e-mail de notificação por padrão:',
		'page_size_activity' => 'Todo o comprimento da página de atividades:',
		'page_size_ask_check_qs' => 'Máximo de perguntas semelhantes para mostrar:',
		'page_size_ask_tags' => 'Máximo de tag de dicas para mostrar:',
		'page_size_home' => 'Comprimento da página inicial:',
		'page_size_hot_qs' => 'Comprimento da página de perguntas populares:',
		'page_size_qs' => 'Comprimento da página de perguntas:',
		'page_size_related_qs' => 'Máximo de perguntas relacionadas:',
		'page_size_search' => 'Perguntas na página de busca:',
		'page_size_tag_qs' => 'Perguntas na página de tag:',
		'page_size_tags' => 'Comprimento da página de tag:',
		'page_size_una_qs' => 'Comprimento de página sem resposta:',
		'page_size_user_posts' => 'Mensagens na página de usuário:',
		'page_size_users' => 'Comprimento da página de usuário:',
		'pages_prev_next' => 'Links para anterior/seguinte nas páginas:',
		'permit_admins' => 'Administradores',
		'permit_all' => 'Alguém',
		'permit_block' => 'Bloqueio ou desbloqueio de usuário ou IPs:',
		'permit_confirmed' => 'Utilizadores registados com e-mail confirmado',
		'permit_create_admins' => 'Criar administradores:',
		'permit_create_eds_mods' => 'Criar editores e moderadores:',
		'permit_create_experts' => 'Criar especialistas:',
		'permit_editors' => 'Editores, Moderadores, Administradores',
		'permit_experts' => 'Especialistas, Editores, Moderadores, Administradores',
		'permit_moderators' => 'Moderadores e administradores',
		'permit_points_confirmed' => 'Registrados & e-mail confirmado & pontos',
		'permit_points' => 'Utilizadores registados com pontos',
		'permit_see_emails' => 'Visualizar e-mail de usuário:',
		'permit_supers' => 'Super Administradores ',
		'permit_users' => 'Utilizadores registados',
		'place_full_below_content' => 'Largura total - Abaixo do conteúdo',
		'place_full_below_footer' => 'Largura total - Abaixo do rodapé',
		'place_full_below_nav' => 'Largura total - Abaixo da navegação',
		'place_full_top' => 'Largura total - Início da página',
		'place_main_below_lists' => 'Principal área - Abaixo da lista',
		'place_main_below_title' => 'Principal área - Abaixo do título',
		'place_main_bottom' => 'Principal área - Bottom',
		'place_main_top' => 'Principal área - Início',
		'place_side_below_categories' => 'Painel lateral - Abaixo da categorias',
		'place_side_below_sidebar' => 'Painel lateral - Abaixo da caixa da barra lateral',
		'place_side_last' => 'Painel lateral - Última',
		'place_side_top' => 'Painel lateral - Início',
		'points_a_selected' => 'Ter sua resposta escolhida como a melhor:',
		'points_a_voted_max_gain' => 'Limite de votos acima em cada resposta:',
		'points_a_voted_max_loss' => 'Limite de votos para baixo em cada resposta:',
		'points_base' => 'Adicionar para todos os usuários:',
		'points_multiple' => 'Multiplicar todos os pontos:',
		'points_per_a_voted' => 'Por cima/baixo votar em sua resposta:',
		'points_per_q_voted' => 'Por cima/baixo voto sobre a sua pergunta:',
		'points_post_a' => 'Postar uma resposta:',
		'points_post_q' => 'Postar uma pergunta:',
		'points_q_voted_max_gain' => 'Limite de votos em cima de cada pergunta:',
		'points_q_voted_max_loss' => 'Limite de votos para baixo em cada questão:',
		'points_select_a' => 'Selecionando a melhor resposta para sua pergunta:',
		'points_vote_down_a' => 'Votar contra uma resposta:',
		'points_vote_down_q' => 'Votar contra uma pergunta:',
		'points_vote_up_a' => 'Voto de uma resposta:',
		'points_vote_up_q' => 'Votação de uma pergunta:',
		'q_urls_remove_accents' => 'Remover acentos de URLs em pergunta:',
		'q_urls_title_length' => 'Comprimento do título da pergunta em URLs:',
		'recaptcha_private_key' => 'Sua chave privada reCAPTCHA:',
		'recaptcha_public_key' => 'Sua chave pública reCAPTCHA:',
		'show_a_form_immediate' => 'Mostrar formulário de resposta imediatamente:',
		'show_always' => 'Sempre',
		'show_c_reply_buttons' => 'Mostrar botões de resposta para comentários:',
		'show_custom_footer' => 'HTML personalizado na parte inferior de cada página:',
		'show_custom_header' => 'HTML personalizado no topo de cada página:',
		'show_custom_home' => 'Conteúdo personalizado na página principal (em vez de Q & A)',
		'show_custom_in_head' => 'HTML personalizado na seção <HEAD> de cada página:',
		'show_custom_sidebar' => 'HTML personalizado na caixa lateral em cada página:',
		'show_custom_sidepanel' => 'HTML personalizado no painel lateral em cada página:',
		'show_home_description' => 'Incluir a descrição <META> para página inicial:',
		'show_if_no_as' => 'Se não houver respostas',
		'show_never' => 'Nunca',
		'show_selected_first' => 'Mover resposta selecionada para o topo:',
		'show_url_links' => 'Detectar link e URLs em texto digitado:',
		'show_user_points' => 'Pontos de exibição ao lado de nomes de usuários:',
		'show_user_titles' => 'Exibir títulos ao lado de nomes de usuários:',
		'show_view_counts' => 'Mostrar o número de pontos de visualização de pergunta:',
		'show_when_created' => 'Mostrar idade de conteúdo do usuário:',
		'site_language' => 'Linguagem para o seu site (^1verificar^2):',
		'site_maintenance' => 'Tirar site do ar para manutenção',
		'site_theme' => 'Tema visual para o seu site:',
		'site_title' => 'Nome do seu site para títulos de página:',
		'site_url' => 'URL para utilizar quando consulta o seu site:',
		'sort_answers_by' => 'Ordenar por respostas:',
		'sort_time' => 'Tempo',
		'sort_votes' => 'Votos',
		'suspend_register_users' => 'Suspender temporariamente novos registos:',
		'tag_separator_comma' => 'Usar somente vírgula como um separador de tag:',
		'tags_or_categories' => 'Classificar perguntas usando:',
		'votes_separated' => 'Mostrar separados para cima e para baixo nos votos:',
		'voting_on_as' => 'Permitir a votação em respostas:',
		'voting_on_q_page_only' => 'Permitir única votação na página de pergunta:',
		'voting_on_qs' => 'Permitir a votação sobre perguntas:',
		'allow_close_questions' => "Permitir que questões sejam fechadas manualmente:",
		'allow_login_email_only' => "Fazer login apenas com nome de utilizador (não nome de utilizador):",
		'allow_self_answer' => "Permitir que utilizadores respondam às suas questões:",
		'captcha_module' => "Usar módulo de captcha:",
		'confirm_user_required' => "Novos utilizadores devem ser confirmados:",
		'default_subject' => "Uma mensagem de ^",
		'do_close_on_select' => "Fechar questões com uma resposta seleccionada:",
		'extra_field_active' => "Campo customizado para informações adicionais relativas à questão:",
		'extra_field_display_label' => "Mostrar a informação adicional em páginas de questão com a etiqueta:",
		'extra_field_display' => "Mostrar a informação adicional em páginas de questão",
		'mailing_body' => "Texto:",
		'mailing_enabled' => "Ativar mailing massivo para todos os utilizadores",
		'mailing_from_email' => "De (e-mail):",
		'mailing_from_name' => "De (nome):",
		'mailing_per_minute' => "Limite de mailing:",
		'mailing_subject' => "Assunto:",
		'max_rate_ip_registers' => "Limite de registos de utilizador:",
		'moderate_anon_post' => "Usar moderação para posts anónimos:",
		'moderate_by_points' => "Usar moderação para utilizadores com poucos pontos:",
		'moderate_notify_admin' => "Enviar um e-mail de notificação quando um post precisar de moderação:",
		'moderate_points_limit' => "Usar moderação para utilizadores menos de:",
		'moderate_unconfirmed' => "Usar moderação se e-mail não confirmado:",
		'option_default' => "Omissão",
		'page_size_q_as' => "Número máximo de questões por página:",
		'permit_delete_users' => "Eliminar utilizadores:",
		'points_per_a_voted_down' => "Por voto negativo na sua resposta:",
		'points_per_a_voted_up' => "Por voto positivo na sua resposta:",
		'points_per_q_voted_down' => "Por voto negativo na sua questão:",
		'points_per_q_voted_up' => "Por voto positivo na sua questão:",
		'search_module' => "Usar módulo de pesquisa:",
		'show_custom_answer' => "Mensagem customizada no formulário de resposta - HTML permitido:",
		'show_custom_ask' => "Mensagem customizada no formulário de questão - HTML permitido:",
		'show_custom_comment' => "Mensagem customizada no formulário de comentário - HTML permitido:",
		'show_custom_register' => "Mensagem customizada no formulário de registo - HTML permitido:",
		'show_custom_welcome' => "Mensagem customizada no e-mail enviado a novos utilizadores registados:",
		'show_fewer_cs_count' => "Se parcialmente escondido, mostrar os mais recentes:",
		'show_fewer_cs_from' => "Esconder parcialmente os comentários se mais do que:",
		'show_full_date_days' => "Mostrar data completa após:",
		'show_message_history' => "Armazenar e mostrar histórico de mensagens privadas:",'show_notice_visitor' => "Mensagem no topo para novos visitantes - HTML permitido:",
		'show_notice_welcome' => "Mensagem no topo para novos utilizadores registados - HTML permitido:",
		'site_theme_mobile' => "Tema para telefones móveis:",
		'smtp_active' => "Enviar e-mail por SMTP em vez de e-mail local",
		'smtp_address' => "Servidor SMTP:",
		'smtp_authenticate' => "Autenticação do servidor de envio SMTP",
		'smtp_password' => "palavra-passe SMTP:",
		'smtp_port' => "Porta do servidor:",
		'smtp_secure_none' => "Nenhuma",
		'smtp_secure' => "ligação segura SMTP:",
		'smtp_username' => "nome de utilizador SMTP:",
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
